---
abstract: 'handle Japan Post Office postal code data'
author:
  - 'Ben Bullock <bkb@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geo-Postcodes-JP
no_index:
  directory:
    - t
    - inc
    - tmpl
    - xt
requires:
  Convert::Moji: 0
  DBD::SQLite: 0
  DBI: 0
  LWP::UserAgent: 0
  Lingua::JA::Moji: 0.11
  perl: 5.008009
resources:
  bugtracker: https://github.com/benkasminbullock/Geo-Postcodes-JP/issues
  homepage: http://prepan.org/module/3Yz7PYrBQM
  repository: https://github.com/benkasminbullock/Geo-Postcodes-JP
version: 0.012
